### ISSUE TITLE
display issue if click the heading ids of TOC first

### ISSUE THREAD

**Issue by actionee** [gabrielcsapo/docusaurus-plugin-image-zoom#3]
Hi Gabriel, if you click the heading ids in the TOC first, there is one strange zoom display issue. Check the video here: [https://imgur.com/nBrrwls](https://imgur.com/nBrrwls). I've tested on macOS and Windows 10 with Edge and Chrome, all the same behavior.

Best!

**Comment by gabrielcsapo** [comment]
Thank you for the issue @act-m ! Can you double check again? I think this was fixed with this https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom/pull/2.

**Comment by RudraSen2** [comment]
I checked it, it is working now with that fix.

**Comment by Ayfel** [comment]
This still happens to me (not by clicking on TOC or anything), I go into my docs, click on an image, it works, click on another and that "white zoom page" shows and I can click again on it again like in the video shared here
